- name: Query Meraki Dashboard
  hosts: craig_lab_wireless
  connection: local
  collections: 
    - cisco.meraki
  tasks:

  - name: query ssids
    meraki_mr_ssid:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: query
    register: result

  - name: display result
    debug:
      msg: "{{ result }}"