name: GitHub Actions chatops
on: [push]
jobs:
  ChatOps:
    runs-on: ubuntu-latest
    steps:
      - run: pip install webexteamssdk
      - name: checkout
        uses: actions/checkout@v3
      - run: python github_webex_push.py
        env:
          WEBEX_TEAMS_ACCESS_TOKEN: ${{ secrets.WEBEX_TOKEN }}